using System;
using DNA.CastleMinerZ.Globalization;
using DNA.Drawing.UI;
using DNA.Drawing.UI.Controls;
using Microsoft.Xna.Framework;

namespace DNA.CastleMinerZ.UI
{
	public class ReleaseNotesScreen : CreditsScreen
	{
		public ReleaseNotesScreen(CastleMinerZGame game, string versionString)
			: base(game._largeFont, game._medLargeFont, game._medFont, false)
		{
			ImageButtonControl imageButtonControl = new ImageButtonControl();
			imageButtonControl.Image = game._uiSprites["BackArrow"];
			imageButtonControl.Font = game._medFont;
			imageButtonControl.LocalPosition = new Point(32, 32);
			imageButtonControl.Pressed += this._backButton_Pressed;
			imageButtonControl.Text = " " + Strings.Back;
			imageButtonControl.ImageDefaultColor = new Color(CMZColors.MenuGreen.ToVector4() * 0.8f);
			base.Controls.Add(imageButtonControl);
			base.AddCreditsItem("Castleminer Z " + versionString + " Release Notes", ItemTypes.Title);
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.9.6", ItemTypes.Header);
			base.AddCreditsItem("Added Lootblocks! These glowing blocks come in two versions, common (blue) and rare (gold).");
			base.AddCreditsItem("Gold loot blocks require a gold pickaxe or higher to open.");
			base.AddCreditsItem("New Scavenger game mode! Scavenger mode follows Survival mode rules, but with plentiful loot blocks for rewarding exploration.");
			base.AddCreditsItem("Survival mode has fewer loot blocks while Endurance modes have none.");
			base.AddCreditsItem("Fixed spawn beacons to work under ground.");
			base.AddCreditsItem("Increased block stack size to 999.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.9.5", ItemTypes.Header);
			base.AddCreditsItem("Stamina adjustments from beta feedback.");
			base.AddCreditsItem("You cannot use stamina in either Endurance mode.");
			base.AddCreditsItem("Whenever you use stamina, there is a cooldown before it regenerates.");
			base.AddCreditsItem("Reduced Sprint speed (previously 2.5x, now 2x).");
			base.AddCreditsItem("Removed the cost for single jumps and raised double jump cost from 15% to 25%.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.9.4", ItemTypes.Header);
			base.AddCreditsItem("New Stamina system!");
			base.AddCreditsItem("Added Sprint by holding Left Shift.");
			base.AddCreditsItem("Added Double jump by pressing space twice.");
			base.AddCreditsItem("Increased the distance you can safely fall before taking damage.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.9.3", ItemTypes.Header);
			base.AddCreditsItem("Fixed Exploration mode to work with hosting online.");
			base.AddCreditsItem("Using Jump while Flying will now move you directly upward.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.9.2", ItemTypes.Header);
			base.AddCreditsItem("Creative mode has been upgraded! Three major changes to this mode:");
			base.AddCreditsItem(" - You can craft anything without needing resources. Build whatever you want!");
			base.AddCreditsItem(" - Dying no longer drops anything from your inventory.");
			base.AddCreditsItem(" - Press F to toggle Fly mode.");
			base.AddCreditsItem("Added a second Lantern model for some additional variety.");
			base.AddCreditsItem("Added a unique model for the Laser Drill.");
			base.AddCreditsItem("Fixed a bug that destroyed all stacks of Recall Beacons when placing one.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.8.8", ItemTypes.Header);
			base.AddCreditsItem("Added a Laser Drill! This modified Laser rifle will cut through dirt and stone but leave valuable resources unharmed and ready to collect.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.8.7", ItemTypes.Header);
			base.AddCreditsItem("Fixed glass and respawn beacons to be diggable. This will not change your respawn location.");
			base.AddCreditsItem("Fixed inventory art for explosives and rocket launchers.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.8.5", ItemTypes.Header);
			base.AddCreditsItem("Added a Respawn Beacon. Place this to set where you spawn after dying!");
			base.AddCreditsItem("Added two sub menus to the crafting menu: Containers and Spawn Points.");
			base.AddCreditsItem("Added a variety of new crates to help organize your base.");
			base.AddCreditsItem("Added window recipes the Other Structures menu.");
			base.AddCreditsItem("Reduced the dust when digging and the smoke on explosions for better visibility.");
			base.AddCreditsItem("Lowered the cost of crafting Stone pickaxes for a smoother starting experience.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.8.1", ItemTypes.Header);
			base.AddCreditsItem("Fix to make sure sticky grenades don't stick to the owner's hand. That hurt!");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.8.0", ItemTypes.Header);
			base.AddCreditsItem("Added Sticky Grenades! Great for precision mining or making sure a zombie don't get away.");
			base.AddCreditsItem("Moved Grenades, TNT and C4 recipes to a new Explosives menu.");
			base.AddCreditsItem("Spooky! Grenades have transformed into Jack-o-lanterns for Halloween!");
			base.AddCreditsItem("Made tooltips show up faster.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.6.1", ItemTypes.Header);
			base.AddCreditsItem("Fixed laser sword crafting bug");
			base.AddCreditsItem("Made LMG stronger");
			base.AddCreditsItem("Zombies can't dig through hardest materials");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.6", ItemTypes.Header);
			base.AddCreditsItem("Added PVP");
			base.AddCreditsItem("Added new gun: LMG");
			base.AddCreditsItem("Added laser sword");
			base.AddCreditsItem("C4 and TNT can be removed with shovels");
			base.AddCreditsItem("Zombies dig through blocks");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.5.4", ItemTypes.Header);
			base.AddCreditsItem("Fixed Auto Climb bugs");
			base.AddCreditsItem("Added Auto Climb Option To Settings");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.5.3", ItemTypes.Header);
			base.AddCreditsItem("Players can walk up blocks without jumping");
			base.AddCreditsItem("Inventory is no longer lost when disconnected");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.5.2", ItemTypes.Header);
			base.AddCreditsItem("Fixed laser weapons being the wrong colors.");
			base.AddCreditsItem("Fixed issues with the game freezing in the menus periodically.");
			base.AddCreditsItem("Fixed the flashing blue line that appeared on SDTVs.");
			base.AddCreditsItem("Huge performance enhancements.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.5.1", ItemTypes.Header);
			base.AddCreditsItem("Fixed performance issue when close to many torches.");
			base.AddCreditsItem("Fixed exploit that allows you to access crates from anywhere.");
			base.AddCreditsItem("Fixed lighting issue caused by large TNT explosions.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.5", ItemTypes.Header);
			base.AddCreditsItem("Added metor crash biome, they start appearing randomly after about distance 300.");
			base.AddCreditsItem("Added new blocks Space Rock and Space Goo, used to make sci-fi tools and weapons");
			base.AddCreditsItem("Added new alien enemy which will defend Space Goo.");
			base.AddCreditsItem("Added new laser weapons, laser weapons remove some blocks when shoot.");
			base.AddCreditsItem("Added explosives TNT,C4 can be set off by hitting or pressing B, also shooting.");
			base.AddCreditsItem("Added grenades, grenades can be cooked by holding right trigger.");
			base.AddCreditsItem("Added RPG launcher.");
			base.AddCreditsItem("Added dragon killing AA rocket which locks on dragons.");
			base.AddCreditsItem("Added Explosive Powder needed to make explosive items, dropped by dragons.");
			base.AddCreditsItem("Dragons are now MUCH harder to kill");
			base.AddCreditsItem("Demons are much harder to kill and will now start to spawn above ground, if you have been to hell.");
			base.AddCreditsItem("Completely reworked sound engine, sounds are now more realistic outdoors and in caves.");
			base.AddCreditsItem("Changed spark effect");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.4.6", ItemTypes.Header);
			base.AddCreditsItem("Added Release Notes");
			base.AddCreditsItem("Minor Bug Fixes");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.4.5", ItemTypes.Header);
			base.AddCreditsItem("Max players has been increased from 4 to 8");
			base.AddCreditsItem("Framerate has been nearly doubled");
			base.AddCreditsItem("Load Times have been cut in half");
			base.AddCreditsItem("Added some detailed descriptions to the menus");
			base.AddCreditsItem("Added a code for Avatar Laser Wars 2, CMZ users will get a full weapon unlock in Avatar Laser Wars 2");
			base.AddCreditsItem("Fixed the problem with Invisible Avatars.");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.4.3", ItemTypes.Header);
			base.AddCreditsItem("Fixed problem where people would start with no inventory");
			base.AddCreditsItem("Fixed problem where all music would play after you spawn/teleport");
			base.AddCreditsItem("Fixed incorrect Menu descriptions on Mode Menu");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.4.2", ItemTypes.Header);
			base.AddCreditsItem("Brightness Setting");
			base.AddCreditsItem("Sound Settings");
			base.AddCreditsItem("Controller Sensitivity Setting");
			base.AddCreditsItem("Zombies make much less noise");
			base.AddCreditsItem("Music is not as loud");
			base.AddCreditsItem("Axe melee damage has been decreased, and is slightly more expensive to make");
			base.AddCreditsItem("Better Error Handling");
			base.AddCreditsItem("Lava is breakable");
			base.AddCreditsItem("'Free Build' has been removed, instead you can play survival with 'No Enemies'");
			base.AddCreditsItem("'Hard' difficulty has been renamed to 'Normal'");
			base.AddCreditsItem("Default difficulty is now 'Normal'");
			base.AddCreditsItem("Original Creator of a world now shows up in browser, even if it is copied");
			base.AddCreditsItem("Made Promo Codes More User friendly");
			base.AddCreditsItem("In Hardcore mode, you no longer start with anything (get ready to punch trees)");
			base.AddCreditsItem("Option to delete storage in game");
			base.AddCreditsItem("Overall difficulty is reduced, especially in the distance");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.4.1", ItemTypes.Header);
			base.AddCreditsItem("Fixed Promo codes not working in network games");
			base.AddCreditsItem("Creative mode can now be played online");
			base.AddCreditsItem("Teleporters don't teleport you to your death if they are not set");
			base.AddCreditsItem("Fixed some duplication bugs");
			base.AddCreditsItem("Removed the original CastleMiner code from the menu ");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.4.0", ItemTypes.Header);
			base.AddCreditsItem("Creative Mode -  Infinite ammo and blocks");
			base.AddCreditsItem("4 New Biome Music Tracks");
			base.AddCreditsItem("Other players worlds are automatically deleted when the game starts");
			base.AddCreditsItem("Animation blending");
			base.AddCreditsItem("Nav Aids: A settable compass  or “Locator”, and a Teleporter ");
			base.AddCreditsItem("New Hardcore Mode");
			base.AddCreditsItem("Dragons now give more resources when killed");
			base.AddCreditsItem("New Enemy: Demon");
			base.AddCreditsItem("More duping Fixes");
			base.AddCreditsItem("Infinite Ammo Fix");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.3.1", ItemTypes.Header);
			base.AddCreditsItem("Fixed dragon spawn problems.");
			base.AddCreditsItem("Joining a game with the wrong version no longer crashes it");
			base.AddCreditsItem("Can no longer attach things to doors. i.e. torches");
			base.AddCreditsItem("Days now tally correctly for acheivements");
			base.AddCreditsItem("Undead Dragon much easier to find");
			base.AddCreditsItem("Dragons spawn much faster in Dragon Endurance");
			base.AddCreditsItem("Fixed another duplication glitch");
			base.AddCreditsItem("Improved Network performance slightly");
			base.AddCreditsItem("Added wait screen to the delete world, so people don't think their Xbox locked up");
			base.AddCreditsItem("Fixed Stat issues, gave all old players free Dragon Endurance unlock");
			base.AddCreditsItem("Fixed a bug with recipes not showing up in the crafting menu");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.3.0", ItemTypes.Header);
			base.AddCreditsItem("Doors... you got em");
			base.AddCreditsItem("Dragon Endurance Mode");
			base.AddCreditsItem("Made shotguns spread less");
			base.AddCreditsItem("Rebalanced the knifes, most are slower and far less durable");
			base.AddCreditsItem("Removed Crosshairs on Shouldered Weapons");
			base.AddCreditsItem("Build Cursor doesn't show up if you can't build. i.e. you are too close to the spot");
			base.AddCreditsItem("Decreased mining particles");
			base.AddCreditsItem("Fixed more Duping bugs");
			base.AddCreditsItem("Fixed crash when bringing up crafting screen with empty inventory");
			base.AddCreditsItem("Fixed nullReference crash when joining a network game");
			base.AddCreditsItem("Fixed Incorrect Dragon Kill Messages");
			base.AddCreditsItem("More Skeletons underground");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.2.1", ItemTypes.Header);
			base.AddCreditsItem("'The Descent' Biome as been restored");
			base.AddCreditsItem("Dragon spawn distances have been adjusted");
			base.AddCreditsItem("Fixed shotgun no spread bug");
			base.AddCreditsItem("Fixed recipes don't show up bug");
			base.AddCreditsItem("Show game difficuly on session browser");
			base.AddCreditsItem("Made all ores slightly richer");
			base.AddCreditsItem("Crate Duplication Bug Fixed");
			base.AddCreditsItem("Xbox Notifications have be relocated on the Screen");
			base.AddCreditsItem("Shotgun quick Reload fix");
			base.AddCreditsItem("Players now notifed of dragon kills");
			base.AddCreditsItem("'Y' will quick transfer between crates/inventory");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.2.0", ItemTypes.Header);
			base.AddCreditsItem("Dragons!");
			base.AddCreditsItem("Fixed Torch Bug");
			base.AddCreditsItem("Reworked Ore Distributions");
			base.AddCreditsItem("Adjusted some recipies slightly");
			base.AddCreditsItem("Made Zombie Drops more generous");
			base.AddCreditsItem("Added Difficulty Setting for Survival");
			base.AddCreditsItem("Fixed problems with splitting items in crates (crashes 'Chainsaw' items, auto heals, etc)");
			base.AddCreditsItem("Fixed zoom problems when switching guns in zoomed states");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.1.0", ItemTypes.Header);
			base.AddCreditsItem("Storage Crates");
			base.AddCreditsItem("Monsters now have Shadows");
			base.AddCreditsItem("You can split stacks with the Right stick in the inventory screen (up down or press for half)");
			base.AddCreditsItem("Compass now works right if you look at it in someone else's hand");
			base.AddCreditsItem("You can now mine snow");
			base.AddCreditsItem("Survival Mode is now hard again");
			base.AddCreditsItem("Iron is less common. But still more than 1.0");
			base.AddCreditsItem("Fixed the AR code. (Sorry Guys)");
			base.AddCreditsItem("Player Inventory now saves in online games too");
			base.AddCreditsItem("Transition Music, day counters now appear in all modes");
			base.AddCreditsItem("Decreased Drop rates on Zombies( killing shouldn't replace mining.)");
			base.AddCreditsItem("Achievement and stats are only counted in Endurance");
			base.AddCreditsItem("You can no longer join games of different versions through invites");
			base.AddCreditsItem("Days now reset when your party dies in Endurance");
			base.AddCreditsItem("B Button now 'Activates' items, such as crates");
			base.AddCreditsItem("Invincible Grey Zombies can now be killed");
			base.AddCreditsItem("Removed annoying purple flash when the game starts");
			base.AddCreditsItem("Improved rendering performance");
			base.AddCreditsItem("Improved Monster Lighting and detail");
			base.AddCreditsItem("You can now Mine Ice");
			base.AddCreditsItem("Hell is Much harder");
			base.AddCreditsItem("Changed Drops for Zombies, zombies now drop wood.");
			base.AddCreditsItem("Item duping exploit fixed");
			base.AddCreditsItem("Pick sounds can no longer be heard everywhere");
			base.AddCreditsItem(" ");
			base.AddCreditsItem("1.0.1", ItemTypes.Header);
			base.AddCreditsItem("On screen direction damage indicator");
			base.AddCreditsItem("Inventory now saves in Survival, and Free Mode");
			base.AddCreditsItem("Torches now show up when you reload a world");
			base.AddCreditsItem("Lightning only lights up the sky instead of the whole screen");
			base.AddCreditsItem("Menu now pauses single player games");
			base.AddCreditsItem("Left Trigger now drops blocks as well as right");
			base.AddCreditsItem("Blocks no longer get dropped if you don't have a square highlighted");
			base.AddCreditsItem("Fixed bug where Iron picks didn't give you diamonds");
			base.AddCreditsItem("Fixed bug where some weapon icons weren't showing up in crafting screen");
			base.AddCreditsItem("Removed 'No Fall Mode' people were just getting stuck running away from zombies");
			base.AddCreditsItem("Fixed bug where walls could not be removed with picks");
			base.AddCreditsItem("Crafting UI now shows ALL recipes needed to make something, even if there are multiple steps");
			base.AddCreditsItem("Crafting UI improved, now clicking on a component takes you to the recipe to make it");
			base.AddCreditsItem("Survival Mode is now significantly easier i.e no more daytime zombies. Endurance is still very hard");
			base.AddCreditsItem("Pickups stay around longer");
			base.AddCreditsItem("Fixed bug where you could repair items for free by passing them to a friend");
			base.AddCreditsItem("Achievement status screen. Shows all Acheivements");
			base.AddCreditsItem("Changes to weapon damage values. Pretty Much made everything stronger");
			base.AddCreditsItem("Knives do much more damge, now take use damage");
			base.AddCreditsItem("No more Zombies in Free Build");
			base.AddCreditsItem("Copper Gold and Iron, Ore are slightly more common");
			base.AddCreditsItem("Fixed bug where Guns of different types were not different colors");
		}

		private void _backButton_Pressed(object sender, EventArgs e)
		{
			base.PopMe();
		}
	}
}
